"""Initial Migration

Revision ID: 162cc5d1ce75
Revises: b2800662e1e9
Create Date: 2021-06-12 22:10:31.983931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162cc5d1ce75'
down_revision = 'b2800662e1e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'pitch_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('pitch_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
